version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: coverage_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        until pg_isready -h db -p 5432; do
          echo waiting for db;
          sleep 2;
        done;
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
